# `Q1 What is a Python library? Why do we use Python libraries?`

### <font color='white'><b>In simple word, Python libraries are collections of functions and methods for use in various applications. They are used to simplify the coding process and enable reuse of code.</b></font>
### <b><span style = "color: orange">There are hundreds of thousands of Python libraries available, covering a wide range of domains, including : </span>
- <b> Data science (NumPy, Pandas, Matplotlib)
- <b> Machine learning (TensorFlow, PyTorch, scikit-learn)
- <b> Web development (Django, Flask, Scrapy)
- <b> And many more
### <b><span style = "color: orange">We use Python Libraries for following reasons : </span>
- <b> Save Time and Effort
- <b> mproved Code Quality
- <b> Enhanced Functionality
- <b> Standardization and Consistency
- <b> Collaboration


# `Q2 What is the difference between Numpy array and List?`

### <font color='white'><b><span style = "color: red;">Type</span> : Numpy array is homogeneous, meaning all elements are of the same data type, while a List is heterogeneous and can contain elements of different data types.</font></b>
---
### <font color='white'><b><span style = "color: red;">Mathematical Operations </span> : Numpy array supports mathematical operations like addition, multiplication, etc., whereas List does not directly support these operations and would require more manual processing. These differences are crucial, as they impact the performance and applicability of each data structure in different scenarios.</font></b>
---
### <font color='white'><b><span style = "color: red;">Memory Allocation </span> : NumPy arrays store data in a compact, contiguous block of memory, which results in less memory overhead compared to Python lists. Whereas Lists in Python are implemented as an array of pointers to objects, rather than a contiguous block of memory for the objects themselves. This results in memory fragmentation and less efficient memory usage.</font></b>

# `Q3 Find the shape, size and dimension of the following array?`
- <b>[[1, 2, 3, 4]
- <b> [5, 6, 7, 8],
- <b> [9, 10, 11, 12]]

In [1]:
import numpy as np

In [2]:
ar = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [3]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## <b><span style = "color: red;">SIZE</span></b>

In [4]:
ar.size

12

## <b><span style = "color: red;">SHAPE</span></b>

In [5]:
ar.shape

(3, 4)

## <b><span style = "color: red;">DIMENSION</span></b>

In [6]:
ar.ndim

2

# `Q4 Write python code to access the first row of the following array?`
- <b>[[1, 2, 3, 4]
- <b> [5, 6, 7, 8],
- <b> [9, 10, 11, 12]]

In [7]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
ar[0]

array([1, 2, 3, 4])

# `Q5 How do you access the element at the third row and fourth column from the given numpy array?`
- <b>[[1, 2, 3, 4]
- <b> [5, 6, 7, 8],
- <b> [9, 10, 11, 12]]

In [9]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
ar[2,3]

12

# `Q6 Write code to extract all odd indexed elements from the given numpy array?`
- <b>[[1, 2, 3, 4]
- <b> [5, 6, 7, 8],
- <b> [9, 10, 11, 12]]

In [11]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
np.extract(ar % 2 == 0 , ar)

array([ 2,  4,  6,  8, 10, 12])

# `Q7 How can you generate a random 3x3 matrix with values between 0 and 1?`

In [13]:
np.random.rand(3, 3)

array([[0.39794517, 0.89595461, 0.44920287],
       [0.46438087, 0.2335205 , 0.18391815],
       [0.9895417 , 0.25959709, 0.77919604]])

# `Q8 Describe the difference between np.random.rand and np.random.randn`

### <font color='white'><b><span style = "color: green">np.random.rand</span> : This function generates samples from a uniform distribution. This means the values will be spread out evenly between 0 (inclusive) and 1 (exclusive). Think of it as picking a number from a ruler that starts at 0 and ends at 1, but you can't pick exactly 1.</font></b>
---
### <font color='white'><b><span style = "color: green">np.random.randn</span> : This function generates samples from a standard normal distribution (also called the Gaussian distribution). This distribution is bell-shaped, with most values concentrated around the mean (which is 0 in this case) and fewer values farther out in the tails. There's a chance of getting negative or positive numbers, and they become less frequent the farther they are from 0.</font></b>
---
- <b> Function	      | Distribution	  |  Range
- <b> np.random.rand  | Uniform	          |  [0, 1)
- <b> np.random.randn | Standard normal	  |  (-∞, ∞)

# `Q9  Write code to increase the dimension of the following array?`
- <b> [[1, 2, 3, 4]
- <b>  [5, 6, 7, 8],
- <b>  [9, 10, 11, 12]]

In [14]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
ar.ndim

2

In [16]:
ar = np.expand_dims(ar,axis = 0)

In [17]:
ar

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [18]:
ar.ndim

3

# `Q10 how to transpose the following array in numpy?`
- <b> [[1, 2, 3, 4]
- <b>  [5, 6, 7, 8],
- <b>  [9, 10, 11, 12]]

In [19]:
ar = np.squeeze(ar)

In [20]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
ar.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [22]:
ar.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# `Q11 Consider the following matrix:`
   - <b>Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
   - <b>Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
## <span style = "color: green"><b>Perform the following operation using Python : </span>
   - <b>1 Index-wise multiplication
   - <b>2 Matrix multiplication
   - <b>3 Add both the matrices
   - <b>4 Subtract matrix B from A
   - <b>5 Divide Matrix B by A

In [23]:
A = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [24]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
B = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [26]:
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## <span style = "color: red"><b>1 Index-wise multiplication</span>

In [27]:
A*B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

## <span style = "color: red"><b>2 Matrix multiplication</span>

In [28]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
matrix_multiplication = np.dot(A, B.T)

In [31]:
matrix_multiplication

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

## <span style = "color: red"><b>3 Add both the matrices</span>

In [32]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
A+B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

## <span style = "color: red"><b>4 Subtract matrix B from A</span>

In [35]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
A-B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## <span style = "color: red"><b>5 Divide Matrix B by A</span>

In [38]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
B/A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# `Q12 Which function in NumPy can be used to swap the byte order of an array?`

- <b>The `np.swapbytes` function in NumPy can be used to swap the byte order of an array.

# `Q13 What is the significance of the np.linalg.inv function?`

- <b>The `np.linalg.inv` function is used to compute the multiplicative inverse of a matrix. This is particularly significant in various mathematical and scientific applications, especially in the field of linear algebra.
- <b>
The multiplicative inverse of a matrix has numerous applications, such as solving systems of linear equations, computing solutions to matrix equations, and in various transformations and calculations involving matrices.

In [41]:
# for Example
arr = np.array([[3,4],[7,8]])
arr

array([[3, 4],
       [7, 8]])

In [42]:
np.linalg.inv(arr)

array([[-2.  ,  1.  ],
       [ 1.75, -0.75]])

# `Q14 What does the np.reshape function do, and how is it used?`

- <b>The `np.reshape` function in NumPy is used to change the shape of an array without changing its data. It allows you to modify the structure of the array while maintaining all the elements within it.
- <b>It creates a new view of the array with the specified shape, as long as the total number of elements in the original array remains the same.

In [43]:
# Let's take an example for better understanding
my_arr = np.arange(12)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
# Reshape into a 2D array with 3 rows and 4 columns
reshaped_arr = np.reshape(my_arr, (3, 4))
reshaped_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# `Q15 What is broadcasting in Numpy?`

- <b>In numpy, `broadcasting` is a feature that allows arrays of different shapes to be added, subtracted, multiplied, or divided element-wise. This means that if the shapes of the arrays being added or matrix multiplication are not compatible, numpy will automatically reshape one of the arrays to make them compatible and perform the operation element-wise, therefore allowing for broadcasting. This is particularly useful for performing operations on arrays with irregular shapes or when performing operations on arrays with different dimensions.

In [45]:
# Let's understand with an example
Array = np.zeros((3,3))    # Creating a 3x3 2D array having value is zero for ecah index by default and datatype is float.
Array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
# Let's create 1D array
Array1 = np.array([1,2,3])

In [47]:
Array1

array([1, 2, 3])

In [48]:
# Broadcasting
result = Array+Array1

In [49]:
result

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])